### PR TITLE
allow multiple creates - validates the current state info

### PR DESCRIPTION
**Pull request by smurawski**
Checks existing state for deployment information, which allows you to run create multiple times and it'll update the existing deployment.

Added a check on for ongoing deployments, allowing create to be re-run after an error and pick up tracking deployments.

### CODE REVIEW

**Comment by smurawski** [comment]
@stuartpreston ^^

**Comment by stuartpreston** [comment]
Noted. Let me know when you think we're good and I'll give it a go and merge.

**Comment by smurawski** [comment]
@stuartpreston I think it's ready to go.  I've been using it the past two days.  I just added a bit more of a log message around the continuation of deployments.

**Comment by stuartpreston** [comment]
:+1: :rocket: Thanks very much @smurawski - will merge and look at putting out a release.

**Comment by stuartpreston** [comment]
:+1: :rocket: Thanks very much @smurawski

**Pull request merged**
